/sys/devices/system/cpu/cpufreq/policy0/scaling_governor#performance:walt
/sys/devices/system/cpu/cpufreq/policy3/scaling_governor#performance:walt
/sys/devices/system/cpu/cpufreq/policy7/scaling_governor#performance:walt
/sys/devices/system/cpu/cpu0/core_ctl/min_cpus#3:1
/sys/devices/system/cpu/cpu3/core_ctl/min_cpus#4:3
/sys/devices/system/cpu/cpu7/core_ctl/min_cpus#1:0
/sys/class/devfreq/1d84000.ufshc/governor#performance:simple_ondemand
/sys/class/devfreq/1d84000.ufshc/min_freq#300000000:75000000
/sys/devices/platform/soc/1d84000.ufshc/clkscale_enable#0:1
/sys/devices/platform/soc/1d84000.ufshc/clkgate_enable#0:1
/proc/irq/32/smp_affinity_list#7:1